# Copied from https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/deployment.yml
name: Deployment

on:
  workflow_dispatch:
  # You can manually trigger a deployment on GitHub.com
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  schedule:
    - cron: '31 13 * * 3'

jobs:
  Build:
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - run: npm ci
      - run: npm test
      - id: daily-version
        uses: fregante/daily-version-action@v1
        name: Create tag if necessary
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.daily-version.outputs.version }}
          release_name: Release ${{ steps.daily-version.outputs.version }}
          draft: false
          prerelease: false
      - name: Update extension's meta
        env:
          VER: ${{ steps.daily-version.outputs.version }}
        run: |
          echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > distribution/SOURCE_URL.txt
          npm run version
      - name: Build project
        run: |
          (cd distribution && zip -r ../twitch-essentials-${{ steps.daily-version.outputs.version }}.zip *)
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./twitch-essentials-${{ steps.daily-version.outputs.version }}.zip
         asset_name: twitch-essentials-${{ steps.daily-version.outputs.version }}.zip
         asset_content_type: application/zip
      - uses: actions/upload-artifact@v2
        with:
          path: distribution

  Chrome:
    needs: Build
    if: github.event_name == 'workflow_dispatch' || needs.Build.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: cd artifact && npx chrome-webstore-upload-cli@1 upload --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  Firefox:
    needs: Build
    if: github.event_name == 'workflow_dispatch' || needs.Build.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: cd artifact && npx web-ext-submit@4
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
